version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=mycloud.settings.local
    depends_on:
      - redis
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A mycloud worker --loglevel=info
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A mycloud beat --loglevel=info
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  redis_data:
