# Generated by Django 4.2 on 2025-08-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='shared_expiry',
            field=models.DateTimeField(blank=True, help_text='Дата и время истечения срока действия ссылки', null=True),
        ),
    ]
