# Generated by Django 4.2 on 2025-08-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_userfile_shared_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='shared_expiry',
            field=models.DateTimeField(blank=True, help_text='Link expiration date and time', null=True),
        ),
    ]
